import { ProductDTO } from '../types';

// ── Mock products for OLCA Rental (vehicle fleet) ────

export const mockProducts: ProductDTO[] = [
  {
    id: 'mock-prod-001',
    erpId: 'ODOO-001',
    nombre: 'Toyota Hilux 4x4',
    descripcion: 'Pickup doble cabina 4x4. Ideal para terrenos difíciles y zonas rurales.',
    categoria: 'Pickups',
    subcategoria: '4x4',
    precioBase: 45000,
    stock: 12,
    imagen: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    especificaciones: { motor: '2.8L Diesel', pasajeros: 5, carga: '1000kg', transmision: 'Manual 6V' },
    marca: 'Toyota',
    modelo: 'Hilux',
    anio: 2024,
  },
  {
    id: 'mock-prod-002',
    erpId: 'ODOO-002',
    nombre: 'Ford Ranger XLT',
    descripcion: 'Pickup mediana, perfecta para logística y distribución urbana.',
    categoria: 'Pickups',
    subcategoria: 'Mediana',
    precioBase: 38000,
    stock: 8,
    imagen: 'https://images.unsplash.com/photo-1501700493788-fa1a4fc9fe62?w=800',
    especificaciones: { motor: '3.2L Diesel', pasajeros: 5, carga: '900kg', transmision: 'Automática 6V' },
    marca: 'Ford',
    modelo: 'Ranger XLT',
    anio: 2023,
  },
  {
    id: 'mock-prod-003',
    erpId: 'ODOO-003',
    nombre: 'Renault Master Furgón',
    descripcion: 'Furgón de gran capacidad para transporte de mercaderías.',
    categoria: 'Furgones',
    subcategoria: 'Gran Porte',
    precioBase: 52000,
    stock: 5,
    imagen: 'https://images.unsplash.com/photo-1586191453773-ae1c77ebe5f7?w=800',
    especificaciones: { motor: '2.3L Diesel', volumen: '13m3', carga: '1500kg', transmision: 'Manual 6V' },
    marca: 'Renault',
    modelo: 'Master',
    anio: 2024,
  },
  {
    id: 'mock-prod-004',
    erpId: 'ODOO-004',
    nombre: 'Mercedes-Benz Sprinter',
    descripcion: 'Minibus o furgón de alta capacidad. Versátil para múltiples usos.',
    categoria: 'Furgones',
    subcategoria: 'Premium',
    precioBase: 75000,
    stock: 3,
    imagen: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800',
    especificaciones: { motor: '2.1L Diesel', volumen: '17m3', carga: '2000kg', transmision: 'Automática' },
    marca: 'Mercedes-Benz',
    modelo: 'Sprinter',
    anio: 2024,
  },
  {
    id: 'mock-prod-005',
    erpId: 'ODOO-005',
    nombre: 'Volkswagen Amarok V6',
    descripcion: 'Pickup premium V6 con el mejor rendimiento de la categoría.',
    categoria: 'Pickups',
    subcategoria: 'Premium',
    precioBase: 58000,
    stock: 6,
    imagen: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=800',
    especificaciones: { motor: '3.0L V6 Diesel', pasajeros: 5, carga: '1100kg', transmision: 'Automática 8V' },
    marca: 'Volkswagen',
    modelo: 'Amarok V6',
    anio: 2024,
  },
  {
    id: 'mock-prod-006',
    erpId: 'ODOO-006',
    nombre: 'Fiat Ducato Furgón',
    descripcion: 'Furgón mediano, económico y confiable para distribución.',
    categoria: 'Furgones',
    subcategoria: 'Mediano',
    precioBase: 34000,
    stock: 10,
    imagen: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800',
    especificaciones: { motor: '2.2L Diesel', volumen: '10m3', carga: '1200kg', transmision: 'Manual 6V' },
    marca: 'Fiat',
    modelo: 'Ducato',
    anio: 2023,
  },
  {
    id: 'mock-prod-007',
    erpId: 'ODOO-007',
    nombre: 'Toyota Land Cruiser 200',
    descripcion: 'SUV de lujo para ejecutivos y zonas de difícil acceso.',
    categoria: 'SUV',
    subcategoria: 'Premium',
    precioBase: 95000,
    stock: 2,
    imagen: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800',
    especificaciones: { motor: '4.5L V8 Diesel', pasajeros: 8, traccion: '4x4', transmision: 'Automática 6V' },
    marca: 'Toyota',
    modelo: 'Land Cruiser 200',
    anio: 2024,
  },
  {
    id: 'mock-prod-008',
    erpId: 'ODOO-008',
    nombre: 'Nissan Frontier',
    descripcion: 'Pickup robusta ideal para trabajo en campo y obra.',
    categoria: 'Pickups',
    subcategoria: '4x4',
    precioBase: 42000,
    stock: 7,
    imagen: 'https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800',
    especificaciones: { motor: '2.5L Diesel', pasajeros: 5, carga: '950kg', transmision: 'Manual 6V' },
    marca: 'Nissan',
    modelo: 'Frontier',
    anio: 2023,
  },
];

export function getMockProducts(): ProductDTO[] {
  return mockProducts;
}

export function getMockProductById(id: string): ProductDTO | undefined {
  return mockProducts.find((p) => p.id === id || p.erpId === id);
}
